  name: Push Image To Docker Hub
  on:
    release:
      types:
        - published
  jobs:
    push_to_docker_hub:
      name: Push To Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push docker image
          uses: docker/build-push-action@v4
          with:
            context: ./docker
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/uuid-centralization:${{ github.event.release.tag_name }}